/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package notatnik;

import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import java.io.*;


/**
 *
 * @author java
 */
public class Okienko1 extends javax.swing.JFrame {

    /**
     * Creates new form Okienko1
     */
    private String StringA= "" , StringB ="", StringC ="";
    public Okienko1() {
        setSize(692,434);
        setLocation(600,300);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); //Czemu nie działa?
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        Kopjuj_t = new javax.swing.JMenuItem();
        Wytnij_t = new javax.swing.JMenuItem();
        Wklei_t = new javax.swing.JMenuItem();
        Usun_t = new javax.swing.JMenuItem();
        Zaznacz_Wszystko_t = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Plik = new javax.swing.JMenu();
        Nowy = new javax.swing.JMenuItem();
        Otworz = new javax.swing.JMenuItem();
        Zapisz = new javax.swing.JMenuItem();
        Zapisz_jako = new javax.swing.JMenuItem();
        Zamknij = new javax.swing.JMenuItem();
        Edycja = new javax.swing.JMenu();
        Kopjuj = new javax.swing.JMenuItem();
        Wytnij = new javax.swing.JMenuItem();
        Wklei = new javax.swing.JMenuItem();
        Usun = new javax.swing.JMenuItem();
        Zaznacz_Wszystko = new javax.swing.JMenuItem();
        Pomoc = new javax.swing.JMenu();
        javax.swing.JMenuItem O_programie = new javax.swing.JMenuItem();

        Kopjuj_t.setText("Kopjuj");
        Kopjuj_t.setToolTipText("");
        Kopjuj_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kopjuj_tActionPerformed(evt);
            }
        });
        jPopupMenu.add(Kopjuj_t);

        Wytnij_t.setText("Wytnij");
        Wytnij_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wytnij_tActionPerformed(evt);
            }
        });
        jPopupMenu.add(Wytnij_t);

        Wklei_t.setText("Wklei");
        Wklei_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wklei_tActionPerformed(evt);
            }
        });
        jPopupMenu.add(Wklei_t);

        Usun_t.setText("Usun");
        Usun_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usun_tActionPerformed(evt);
            }
        });
        jPopupMenu.add(Usun_t);

        Zaznacz_Wszystko_t.setText("Zaznacz Wszystko");
        Zaznacz_Wszystko_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zaznacz_Wszystko_tActionPerformed(evt);
            }
        });
        jPopupMenu.add(Zaznacz_Wszystko_t);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jTextPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPane1FocusLost(evt);
            }
        });
        jTextPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextPane1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextPane1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane1);

        Plik.setText("Plik");

        Nowy.setText("Nowy");
        Nowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NowyActionPerformed(evt);
            }
        });
        Plik.add(Nowy);

        Otworz.setText("Otworz");
        Otworz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtworzActionPerformed(evt);
            }
        });
        Plik.add(Otworz);

        Zapisz.setText("Zapisz");
        Plik.add(Zapisz);

        Zapisz_jako.setText("Zapisz jako...");
        Zapisz_jako.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zapisz_jakoActionPerformed(evt);
            }
        });
        Plik.add(Zapisz_jako);

        Zamknij.setText("Zamknij");
        Zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZamknijActionPerformed(evt);
            }
        });
        Plik.add(Zamknij);

        jMenuBar1.add(Plik);

        Edycja.setText("Edycja");

        Kopjuj.setText("Kopjuj");
        Kopjuj.setToolTipText("");
        Kopjuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KopjujActionPerformed(evt);
            }
        });
        Edycja.add(Kopjuj);

        Wytnij.setText("Wytnij");
        Wytnij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WytnijActionPerformed(evt);
            }
        });
        Edycja.add(Wytnij);

        Wklei.setText("Wklei");
        Wklei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WkleiActionPerformed(evt);
            }
        });
        Edycja.add(Wklei);

        Usun.setText("Usun");
        Usun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsunActionPerformed(evt);
            }
        });
        Edycja.add(Usun);

        Zaznacz_Wszystko.setText("Zaznacz Wszystko");
        Zaznacz_Wszystko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zaznacz_WszystkoActionPerformed(evt);
            }
        });
        Edycja.add(Zaznacz_Wszystko);

        jMenuBar1.add(Edycja);

        Pomoc.setText("Pomoc");

        O_programie.setText("O programie");
        O_programie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_programieActionPerformed(evt);
            }
        });
        Pomoc.add(O_programie);

        jMenuBar1.add(Pomoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void O_programieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_programieActionPerformed
        // TODO add your handling code here:
        Okienko1 okno = new Okienko1();
        okno.setVisible(true);
        okno.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        okno.oprogramie();
    }//GEN-LAST:event_O_programieActionPerformed
    private void oprogramie(){
    jTextPane1.setText("Czesc");
    }
    private void Kopjuj_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kopjuj_tActionPerformed
        StringB = jTextPane1.getSelectedText();
        // TODO add your handling code here:
    }//GEN-LAST:event_Kopjuj_tActionPerformed

    private void Wytnij_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wytnij_tActionPerformed
        StringB = jTextPane1.getSelectedText();
        StringC = "";
        int sel_start = jTextPane1.getSelectionStart();
        int sel_end = jTextPane1.getSelectionEnd();
        for (int i=0 ; i < StringA.length() ; i++ ){
            if (i < sel_start || i > sel_end - 1)
            StringC = StringC + StringA.charAt(i);
        }
        StringA = StringC;
        jTextPane1.setText(StringA);
        // TODO add your handling code here:
    }//GEN-LAST:event_Wytnij_tActionPerformed

    private void Wklei_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wklei_tActionPerformed
        StringC = "";
        int sel_start = jTextPane1.getSelectionStart();
        int sel_end = jTextPane1.getSelectionEnd();
        int pom = 0;
        for (int i=0 ; i < StringA.length() ; i++ ){
            if (i < sel_start || i > sel_end -1)
            StringC = StringC + StringA.charAt(i);
            else
            {
                StringC = StringC + StringB;
                i = sel_end - 1;
                pom = 1;
            }    
        }
        if (pom == 1)
        StringA = StringC;
        else
        StringA = StringC + StringB;
        jTextPane1.setText(StringA); 
        // TODO add your handling code here:
    }//GEN-LAST:event_Wklei_tActionPerformed

    private void Usun_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usun_tActionPerformed
        StringC = "";
        int sel_start = jTextPane1.getSelectionStart();
        int sel_end = jTextPane1.getSelectionEnd();
        for (int i=0 ; i < StringA.length() ; i++ ){
            if (i < sel_start || i > sel_end - 1)
            StringC = StringC + StringA.charAt(i);
        }
        StringA = StringC;
        jTextPane1.setText(StringA);
        // TODO add your handling code here:
    }//GEN-LAST:event_Usun_tActionPerformed

    private void Zaznacz_Wszystko_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zaznacz_Wszystko_tActionPerformed
        jTextPane1.setSelectionStart(0);
        jTextPane1.setSelectionEnd(StringA.length());
        // TODO add your handling code here:
    }//GEN-LAST:event_Zaznacz_Wszystko_tActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (evt.isPopupTrigger()){
            showPopupMenu(evt);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if (evt.isPopupTrigger()){
            showPopupMenu(evt);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseReleased

    private void jTextPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPane1MousePressed
        if (evt.isPopupTrigger()){
            showPopupMenu(evt);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane1MousePressed

    private void jTextPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPane1MouseReleased
        if (evt.isPopupTrigger()){
            showPopupMenu(evt);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane1MouseReleased

    private void jTextPane1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPane1FocusLost
        StringA = jTextPane1.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane1FocusLost

    private void KopjujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KopjujActionPerformed
        Kopjuj_tActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_KopjujActionPerformed

    private void WytnijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WytnijActionPerformed
        Wytnij_tActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_WytnijActionPerformed

    private void WkleiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WkleiActionPerformed
        Wklei_tActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_WkleiActionPerformed

    private void UsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsunActionPerformed
        Usun_tActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_UsunActionPerformed

    private void Zaznacz_WszystkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zaznacz_WszystkoActionPerformed
        Zaznacz_Wszystko_tActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_Zaznacz_WszystkoActionPerformed

    private void ZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZamknijActionPerformed
        this.setEnabled(false);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ZamknijActionPerformed

    private void NowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NowyActionPerformed
        Okienko1 okno = new Okienko1();
        okno.setVisible(true);
        okno.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        // TODO add your handling code here:
    }//GEN-LAST:event_NowyActionPerformed

    private void OtworzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtworzActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
       
            File file = new File(chooser.getSelectedFile().getAbsolutePath()); //biore scieżke bezwzgledna do pliku
            try{
                BufferedReader read = new BufferedReader(new FileReader(file));
                do  {
                    StringC = read.readLine();
                    if(StringC != null)
                    StringA +=StringC + "\r"; 
                    }while(StringC != null);
                }
           catch(Exception e){}
           jTextPane1.setText(StringA);      
           
        // load from file
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_OtworzActionPerformed

    private void Zapisz_jakoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zapisz_jakoActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showSaveDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
           File file = new File(chooser.getSelectedFile().getAbsolutePath());
           try{
               BufferedWriter write = new BufferedWriter(new FileWriter(file));
                
                write.write(StringA);
                
                
                write.close();
           } catch(Exception e){}
           jTextPane1.setText(StringA);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Zapisz_jakoActionPerformed
    private void showPopupMenu(java.awt.event.MouseEvent e){
        jPopupMenu.show(this, e.getX(), e.getY());
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okienko1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okienko1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okienko1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okienko1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okienko1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edycja;
    private javax.swing.JMenuItem Kopjuj;
    private javax.swing.JMenuItem Kopjuj_t;
    private javax.swing.JMenuItem Nowy;
    private javax.swing.JMenuItem Otworz;
    private javax.swing.JMenu Plik;
    private javax.swing.JMenu Pomoc;
    private javax.swing.JMenuItem Usun;
    private javax.swing.JMenuItem Usun_t;
    private javax.swing.JMenuItem Wklei;
    private javax.swing.JMenuItem Wklei_t;
    private javax.swing.JMenuItem Wytnij;
    private javax.swing.JMenuItem Wytnij_t;
    private javax.swing.JMenuItem Zamknij;
    private javax.swing.JMenuItem Zapisz;
    private javax.swing.JMenuItem Zapisz_jako;
    private javax.swing.JMenuItem Zaznacz_Wszystko;
    private javax.swing.JMenuItem Zaznacz_Wszystko_t;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
    
}
